### ISSUE TITLE
Npm install results in 404 not found

### ISSUE THREAD

**Issue by ThomasVeld** [accept-nano/accept-nano-client#11]
Hi,

when trying to npm install / yarn add I do get the following error:

Not Found - GET https://registry.npmjs.org/accept-nano-client - Not found

--
Edit: I've downloaded the repo directly, the demo works AMAZING!

**Comment by BatuAksoy** [comment]
Hey @ThomasVeld,
Sorry for the inconvenience. It should be "**@accept-nano/client**". Package is [here](https://www.npmjs.com/package/@accept-nano/client). I will update readme accordingly. Thanks for the heads up!
